# Generated by Django 4.1.9 on 2023-06-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="name", new_name="firstname",
        ),
    ]
