# Generated by Django 4.1.10 on 2023-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_rename_name_users_firstname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=3)),
                ("room_capacity", models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="room_num",
            field=models.CharField(max_length=255),
        ),
    ]
